@startuml
package "Frontend" {
    [Web App] #E3F2FD
    [Mobile App] #E3F2FD
    [Chatbot (Futuro)] #E3F2FD
}

package "BFF" {
    [BFF Web] #E3F2FD
    [BFF Mobile] #E3F2FD
}

package "Backend" {
    [bookbrew-authentication-service] #E3F2FD
    [bookbrew-notification-service] #E3F2FD
    [bookbrew-recommendation-service] #E3F2FD
    [bookbrew-promotion-service] #E3F2FD
    [bookbrew-order-service] #E3F2FD
    [bookbrew-customer-service] #E3F2FD
    [bookbrew-product-service] #E3F2FD
    [bookbrew-analytics-service] #E3F2FD
    [bookbrew-support-service] #E3F2FD
    [bookbrew-payment-service] #E3F2FD
}

package "Databases" {
    database MySQL as MySQL #BBDEFB
    database MongoDB as MongoDB #BBDEFB
    [Redis Cache] #BBDEFB
}

package "External Services" {
    [Stripe] #FFE082
    [API de Endereços (CEP)] #FFE082
    [Instagram] #FFE082
    [AI Curadoria] #FFE082
}

package "Infrastructure" {
    [Docker] #C5E1A5
    [Message Queue] #C5E1A5
}

[Web App] --> [BFF Web]
[Mobile App] --> [BFF Mobile]

[BFF Web] --> [bookbrew-authentication-service]
[BFF Web] --> [bookbrew-customer-service]
[BFF Web] --> [bookbrew-product-service]
[BFF Web] --> [bookbrew-order-service]
[BFF Web] --> [bookbrew-promotion-service]
[BFF Web] --> [bookbrew-notification-service]
[BFF Web] --> [bookbrew-recommendation-service]

[BFF Mobile] --> [bookbrew-authentication-service]
[BFF Mobile] --> [bookbrew-customer-service]
[BFF Mobile] --> [bookbrew-product-service]
[BFF Mobile] --> [bookbrew-order-service]
[BFF Mobile] --> [bookbrew-promotion-service]
[BFF Mobile] --> [bookbrew-notification-service]
[BFF Mobile] --> [bookbrew-recommendation-service]

[bookbrew-authentication-service] --> MySQL
[bookbrew-customer-service] --> MySQL
[bookbrew-product-service] --> MongoDB
[bookbrew-order-service] --> MySQL
[bookbrew-notification-service] --> [Redis Cache]
[bookbrew-recommendation-service] --> [AI Curadoria]
[bookbrew-payment-service] --> [Stripe]
[bookbrew-support-service] --> [Instagram]
[API de Endereços (CEP)] --> [bookbrew-customer-service]

[bookbrew-notification-service] --> [Message Queue]
[bookbrew-recommendation-service] --> [Message Queue]
[bookbrew-order-service] --> [Message Queue]
@enduml
