@startuml
!define RECTANGLE_COLOR #E3F2FD
!define RECTANGLE_BORDER #90CAF9

package "Frontend" as Frontend {
    [Mobile App] <<RECTANGLE_COLOR>>
    [Web App] <<RECTANGLE_COLOR>>
}

package "BFFs (Backend for Frontend)" as BFFs {
    [bookbrew-bff-mobile] <<RECTANGLE_COLOR>>
    [bookbrew-bff-web] <<RECTANGLE_COLOR>>
}

package "Microsserviços Internos" as Backend {
    [bookbrew-authentication-service] <<RECTANGLE_COLOR>>
    [bookbrew-notification-service] <<RECTANGLE_COLOR>>
    [bookbrew-recommendation-service] <<RECTANGLE_COLOR>>
    [bookbrew-promotion-service] <<RECTANGLE_COLOR>>
    [bookbrew-order-service] <<RECTANGLE_COLOR>>
    [bookbrew-customer-service] <<RECTANGLE_COLOR>>
    [bookbrew-product-service] <<RECTANGLE_COLOR>>
    [bookbrew-analytics-service] <<RECTANGLE_COLOR>>
    [bookbrew-support-service] <<RECTANGLE_COLOR>>
    [bookbrew-payment-service] <<RECTANGLE_COLOR>>
}

package "Serviços Externos" as External {
    [Stripe]
    [API de Endereços (CEP)]
    [Instagram]
    [IA Curadoria]
}

' Frontend Interage com BFFs
Frontend --> [bookbrew-bff-mobile]
Frontend --> [bookbrew-bff-web]

' BFFs interagem com microsserviços
[bookbrew-bff-mobile] --> [bookbrew-authentication-service]
[bookbrew-bff-mobile] --> [bookbrew-notification-service]
[bookbrew-bff-mobile] --> [bookbrew-recommendation-service]
[bookbrew-bff-mobile] --> [bookbrew-promotion-service]
[bookbrew-bff-mobile] --> [bookbrew-order-service]
[bookbrew-bff-mobile] --> [bookbrew-customer-service]
[bookbrew-bff-mobile] --> [bookbrew-product-service]
[bookbrew-bff-mobile] --> [bookbrew-analytics-service]
[bookbrew-bff-mobile] --> [bookbrew-support-service]
[bookbrew-bff-mobile] --> [bookbrew-payment-service]

[bookbrew-bff-web] --> [bookbrew-authentication-service]
[bookbrew-bff-web] --> [bookbrew-notification-service]
[bookbrew-bff-web] --> [bookbrew-recommendation-service]
[bookbrew-bff-web] --> [bookbrew-promotion-service]
[bookbrew-bff-web] --> [bookbrew-order-service]
[bookbrew-bff-web] --> [bookbrew-customer-service]
[bookbrew-bff-web] --> [bookbrew-product-service]
[bookbrew-bff-web] --> [bookbrew-analytics-service]
[bookbrew-bff-web] --> [bookbrew-support-service]
[bookbrew-bff-web] --> [bookbrew-payment-service]

' Integrações Externas
[bookbrew-payment-service] --> [Stripe]
[API de Endereços (CEP)] --> Backend
[Instagram] --> [bookbrew-notification-service]
[IA Curadoria] --> [bookbrew-recommendation-service]

@enduml
